import os
import pandas as pd
import glob

def get_latest_results_csv():
    # Search for all results.csv files in the project root
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    search_pattern = os.path.join(base_dir, "**", "results.csv")
    files = glob.glob(search_pattern, recursive=True)
    
    if not files:
        return None
        
    # Sort by modification time to get the latest run
    latest_file = max(files, key=os.path.getmtime)
    return latest_file

def main():
    results_path = get_latest_results_csv()
    
    if not results_path:
        print("Error: Could not find results.csv.")
        print("Please make sure you have successfully run the training script first!")
        return
        
    print("==================================================")
    print("📊 AI MODEL PERFORMANCE EVALUATION")
    print("==================================================\n")
    
    # Read the YOLOv8 results CSV
    # YOLO classification CSV columns usually have extra whitespace, so we strip them
    df = pd.read_csv(results_path)
    df.columns = df.columns.str.strip()
    
    # Get the data from the final epoch
    final_epoch = df.iloc[-1]
    
    # Extract Accuracy and Loss
    top1_acc = final_epoch.get('metrics/accuracy_top1', 0) * 100
    val_loss = final_epoch.get('val/loss', 0)
    
    print(f"✅ Top-1 Accuracy:  {top1_acc:.2f}%")
    print(f"✅ Validation Loss: {val_loss:.4f} (This is used instead of MSE for Classification)")
    
    print("\n--------------------------------------------------")
    print("How to find Precision, Recall, and F1-Score:")
    print("--------------------------------------------------")
    print("For AI Classification tasks, YOLOv8 doesn't output a single global 'Recall' number.")
    print("Instead, it calculates Precision, Recall, and F1-score for EVERY single crop disease separately.")
    print("\nTo see these values, open the confusion matrix image generated by YOLO:")
    print("📂 PATH: backend/scripts/runs/classify/disease_detection_model/confusion_matrix_normalized.png")
    print("\nIn that image:")
    print("- The Diagonal line shows your Recall (True Positive Rate) for each disease.")
    print("- Darker colors on the diagonal mean higher F1 and Recall scores!")

if __name__ == "__main__":
    main()
